- name: Instalar Chrome y Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      - name: Ejecutar script con Xvfb (Anti-Bot)
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          MIS_COOKIES: ${{ secrets.MIS_COOKIES }}
        # Usamos --auto-servernum para evitar conflictos de pantalla
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node index.js